### ISSUE TITLE
Error in gendata/gendb.py File

### ISSUE THREAD

**Issue by Zinia17** [zhezh/TotalCapture-Toolbox#9]
Hi, 
I have followed the instruction to process total capture dataset you have described. After organizing all the fills as you have mentioned, while I run the command, `python gendata/gendb.py` it was running perfectly and giving verbose like the followings:
100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.29it/s]
100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.34it/s]
100%|███████████████████████████████████████| 2421/2421 [00:32<00:00, 74.43it/s]

But unfortunately after a long time it gives a key error as bellow: 
`Traceback (most recent call last):
  File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 368, in <module>
    train_dataset = extract_db(config, train_dir_meta, cameras)
  File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 129, in extract_db
    vid_frame_num = int(vid_info['video']['@nb_frames'])
KeyError: 'video' 
`
Can you please help me resolve it?

**Comment by akusdhgfu** [comment]
> Hi, I have followed the instruction to process total capture dataset you have described. After organizing all the fills as you have mentioned, while I run the command, `python gendata/gendb.py` it was running perfectly and giving verbose like the followings: 100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.29it/s] 100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.34it/s] 100%|███████████████████████████████████████| 2421/2421 [00:32<00:00, 74.43it/s]
> 
> But unfortunately after a long time it gives a key error as bellow: `Traceback (most recent call last): File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 368, in <module> train_dataset = extract_db(config, train_dir_meta, cameras) File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 129, in extract_db vid_frame_num = int(vid_info['video']['@nb_frames']) KeyError: 'video' ` Can you please help me resolve it?

I also encountered the same problem, have you solved it?
![08ef4be28bb8cc6e24ace5e961c63d5](https://github.com/zhezh/TotalCapture-Toolbox/assets/101231420/73cd66a4-e6bf-4cf8-af91-ef73eccd8225)

**Comment by Zinia17** [comment]
> > Hi, I have followed the instruction to process total capture dataset you have described. After organizing all the fills as you have mentioned, while I run the command, `python gendata/gendb.py` it was running perfectly and giving verbose like the followings: 100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.29it/s] 100%|███████████████████████████████████████| 3385/3385 [00:45<00:00, 74.34it/s] 100%|███████████████████████████████████████| 2421/2421 [00:32<00:00, 74.43it/s]
> > But unfortunately after a long time it gives a key error as bellow: `Traceback (most recent call last): File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 368, in <module> train_dataset = extract_db(config, train_dir_meta, cameras) File "./TotalCapture-Toolbox-master/gendata/gendb.py", line 129, in extract_db vid_frame_num = int(vid_info['video']['@nb_frames']) KeyError: 'video' ` Can you please help me resolve it?
> 
> I also encountered the same problem, have you solved it? ![08ef4be28bb8cc6e24ace5e961c63d5](https://private-user-images.githubusercontent.com/101231420/295095454-73cd66a4-e6bf-4cf8-af91-ef73eccd8225.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MDQ5NjMwNTQsIm5iZiI6MTcwNDk2Mjc1NCwicGF0aCI6Ii8xMDEyMzE0MjAvMjk1MDk1NDU0LTczY2Q2NmE0LWU2YmYtNGNmOC1hZjkxLWVmNzNlY2NkODIyNS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwMTExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDExMVQwODQ1NTRaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT02MGNmNjEwMzQ5ZjZjZWE0ODUzOTE3ODA2MmQ0N2U0NmVhNDFhOGJmODkzZTEzNTZhMWYwMTM5M2FmNTgzODkwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.fN6J97f7W6e_stSq-yfTDUGouCodiCZP63fS_3XQGQA)

I could not solve it yet.

**Comment by akusdhgfu** [comment]
I have successfully solved it. The reason for the error is that there are only MP4 files of 6 cameras in the s2_mattes/S2/acting1 folder, while other folders have MP4 files of 8 cameras. I also emailed the release team of the dataset and they said there was an issue with the remaining camera data.

**Comment by Zinia17** [comment]
Nice. So, did you executed the code for 6 camera?

**Comment by akusdhgfu** [comment]
> Nice. So, did you executed the code for 6 camera?

Yes, I modified the code so that it ignores the two missing MP4 files in the S2/acting1 folder and it can run smoothly.
